# Generated by Django 6.1.1 on 2026-09-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='capcity',
            new_name='capacity',
        ),
    ]
